Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -285,39 +285,40 @@ runs:
                  echo "::group:: Downloading 3rd gcc"
                  if [ ! -z ${{ inputs.other-gcc64-url }} ] && [ ! -z ${{ inputs.other-gcc32-url }} ]; then
                      if [ -d $HOME/clang ]; then
-                     export OTHER_GCC64_URL=${{ inputs.other-gcc64-url }}
-                     export OTHER_GCC32_URL=${{ inputs.other-gcc32-url }}
-                     mkdir -p -v $HOME/gcc-64             
-                     if [[ "$OTHER_GCC64_URL" == *'.tar.gz' ]]; then    
-                          aria2c -o gcc-aarch64.tar.gz "$OTHER_GCC64_URL"
-                          tar -C $HOME/gcc-64 -zxf gcc-aarch64.tar.gz
-                     elif [[ "$OTHER_GCC64_URL" == *'.zip' ]]; then
-                          aria2c -o gcc-aarch64.zip "$OTHER_GCC64_URL" 
-                          unzip -q gcc-aarch64.zip -d $HOME/gcc-64
-                     elif [[ "$OTHER_GCC64_URL" == *'.tar.xz' ]]; then
-                          aria2c -o gcc-aarch64.tar.xz "$OTHER_GCC64_URL"         
-                          tar -C $HOME/gcc-64 -xf gcc-aarch64.tar.xz
-                  else
-                      git clone "$OTHER_GCC64_URL" $HOME/gcc-64 --depth=${{ inputs.depth }} -b ${{ inputs.other-gcc64-branch }}
-              fi
+                         export OTHER_GCC64_URL=${{ inputs.other-gcc64-url }}
+                         export OTHER_GCC32_URL=${{ inputs.other-gcc32-url }}
+                         mkdir -p -v $HOME/gcc-64             
+                         if [[ "$OTHER_GCC64_URL" == *'.tar.gz' ]]; then    
+                              aria2c -o gcc-aarch64.tar.gz "$OTHER_GCC64_URL"
+                              tar -C $HOME/gcc-64 -zxf gcc-aarch64.tar.gz
+                         elif [[ "$OTHER_GCC64_URL" == *'.zip' ]]; then
+                              aria2c -o gcc-aarch64.zip "$OTHER_GCC64_URL" 
+                              unzip -q gcc-aarch64.zip -d $HOME/gcc-64
+                         elif [[ "$OTHER_GCC64_URL" == *'.tar.xz' ]]; then
+                              aria2c -o gcc-aarch64.tar.xz "$OTHER_GCC64_URL"         
+                              tar -C $HOME/gcc-64 -xf gcc-aarch64.tar.xz
+                         else
+                              git clone "$OTHER_GCC64_URL" $HOME/gcc-64 --depth=${{ inputs.depth }} -b ${{ inputs.other-gcc64-branch }}
+                         fi
+                     fi
 
-              mkdir -p -v $HOME/gcc-32
-              if [[ "$OTHER_GCC32_URL" == *'.tar.gz' ]]; then
-                    aria2c -o gcc-arm.tar.gz "$OTHER_GCC32_URL"
-                    tar -C $HOME/gcc-32 -zxf gcc-arm.tar.gz
-              elif [[ "$OTHER_GCC32_URL" == *'.zip' ]]; then
-                    aria2c -o gcc-arm.zip "$OTHER_GCC32_URL" 
-                    unzip -q gcc-arm.zip -d $HOME/gcc-32
-              elif [[ "$OTHER_GCC32_URL" == *'.tar.xz' ]]; then
-                    aria2c -o gcc-arm.tar.xz "$OTHER_GCC32_URL"         
-                    tar -C $HOME/gcc-32 -xf gcc-arm.tar.xz
-              else
-                  git clone "$OTHER_GCC32_URL" $HOME/gcc-32 --depth=${{ inputs.depth }} -b ${{ inputs.other-gcc32-branch }}  
-             fi                  
-         fi
-         else
-             echo "Error: Please enable 3rd other-gcc32-url and other-gcc64-url." && exit 15
-         fi
+                     mkdir -p -v $HOME/gcc-32
+                     if [[ "$OTHER_GCC32_URL" == *'.tar.gz' ]]; then
+                           aria2c -o gcc-arm.tar.gz "$OTHER_GCC32_URL"
+                           tar -C $HOME/gcc-32 -zxf gcc-arm.tar.gz
+                     elif [[ "$OTHER_GCC32_URL" == *'.zip' ]]; then
+                           aria2c -o gcc-arm.zip "$OTHER_GCC32_URL" 
+                           unzip -q gcc-arm.zip -d $HOME/gcc-32
+                     elif [[ "$OTHER_GCC32_URL" == *'.tar.xz' ]]; then
+                           aria2c -o gcc-arm.tar.xz "$OTHER_GCC32_URL"         
+                           tar -C $HOME/gcc-32 -xf gcc-arm.tar.xz
+                     else
+                         git clone "$OTHER_GCC32_URL" $HOME/gcc-32 --depth=${{ inputs.depth }} -b ${{ inputs.other-gcc32-branch }}  
+                     fi                  
+                 fi
+             else
+                 echo "Error: Please enable 3rd other-gcc32-url and other-gcc64-url." && exit 15
+             fi
          else
              echo "::group:: Downloading AOSP GCC"
              if [ -d $HOME/clang ]; then
@@ -334,10 +335,10 @@ runs:
                  git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/ --depth=1 -b android${{ inputs.android-version }}-release $HOME/gcc-32
              fi
          fi
+
          if [ ! -d $HOME/gcc-64/bin/ ] || [ ! -d $HOME/gcc-32/bin/ ]; then
              [ ! -d $HOME/gcc-64/bin/ ] && mv $HOME/gcc-64/*/* $HOME/gcc-64/
              [ ! -d $HOME/gcc-32/bin/ ] && mv $HOME/gcc-32/*/* $HOME/gcc-32/
-             fi
          fi
          echo "::endgroup::"
 
